### ISSUE TITLE
Welcome to Leetcode75 Discussions!

### ISSUE THREAD

**Issue by smartytushar** [Black-D3vil007/Leetcode75#52]
### Discussed in https://github.com/Black-D3vil007/Leetcode75/discussions/51

<div type='discussions-op-text'>

<sup>Originally posted by **Black-D3vil007** October 11, 2022</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by Black-D3vil007** [comment]
Thanks for this.
